name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  version_bump_job:
    if: github.event_name == 'push' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Increment version
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: DotNet Bump Versions
        uses: SiqiLu/dotnet-bump-version@2.0.0
        with:
          # Version files to bump version. You can use Glob pattern string (like "**/*.csproj") or Glob patterns array json string (like "["**/*.csproj", "v1.version", "**/*.version.json", "!v2.version.json"]"). Patterns supported by Globby are supported. Leading ! changes the meaning of an include pattern to exclude.
          version_files: "**/*.csproj" # optional, default is **/*.csproj
          # Control which part of the version to be bumped. The input must have four parts(split by "."). Example: "1.0.0.0": Bump the major part of the version.  2.3.4.5 => 3.0.0.0 "0.1.0.0": Bump the minor part of the version.  2.3.4.5 => 2.4.0.0 "0.0.1.0": Bump the patch part of the version.  2.3.4.5 => 2.3.5.0 "0.0.0.1": Bump the minor part of the version.  2.3.4.5 => 2.3.4.6 "1.0.1.0": Bump the major and the patch part of the version.  2.3.4.5 => 3.0.5.0 "1.1.1.1": Bump all the parts of the version.  2.3.4.5 => 3.4.5.6 
          version_mask: 0.0.1.0
          # Overwrite the bumped version. The input must have four parts(split by "."). Use this input option to overwrite the version or part of the version. If you want to modified all versions in the version files to a specifed version number, you should use this input option. If you do not want overwrite the version or any part of the version, you should just ignore this input option. Example: "*.*.*.*" does not overwrite ant part of the version. "1.*.*.*" overwrite the major part with number 1. "*.*.*.Alpha" overwrite the build part with string "Alpha". "*.*.*.github.run_number" overwrite the build part with "github.run_number".
          version_overwrite: "*.*.*.*"
          # The github token to push changes.
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MEADOW_09B6C550F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Client" # App source code path
          api_location: "Api" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MEADOW_09B6C550F }}
          action: "close"
